CREATE TABLE inventario (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            sku_vinilo VARCHAR(50) NOT NULL UNIQUE,
                            cantidad_disponible INT NOT NULL,
                            ubicacion_bodega VARCHAR(100) NOT NULL,
                            ultima_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);