CREATE TABLE carritos (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          usuario_id BIGINT NOT NULL,
                          total INT NOT NULL DEFAULT 0,
                          estado VARCHAR(50) NOT NULL
);

CREATE TABLE carrito_items (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               carrito_id BIGINT NOT NULL,
                               sku_vinilo VARCHAR(50) NOT NULL,
                               cantidad INT NOT NULL,
                               precio_unitario INT NOT NULL,
                               FOREIGN KEY (carrito_id) REFERENCES carritos(id) ON DELETE CASCADE
);