CREATE TABLE pedidos (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         rut_cliente VARCHAR(50) NOT NULL,
                         total INT NOT NULL,
                         estado VARCHAR(50) NOT NULL,
                         fecha_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pedido_items (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              pedido_id BIGINT NOT NULL,
                              sku_vinilo VARCHAR(50) NOT NULL,
                              cantidad INT NOT NULL,
                              precio_unitario INT NOT NULL,
                              FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE
);